name: Build & Release APK

on:
  push:
    tags:
      - '*'  # 任何 tag 都会触发
  workflow_dispatch:  # 也支持手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create keystore directory
        run: mkdir -p app/keystore

      - name: Decode keystore to app/keystore
        run: |
          echo "${{ secrets.KEYSTORE_B64 }}" | base64 -d > app/keystore/my-release-key.jks
          ls -l app/keystore  # 可选调试

      - name: Grant gradlew permission
        run: chmod +x ./gradlew

      - name: Build Release APK
        run: |
          ./gradlew assembleRelease \
            -PKEYSTORE_FILE=app/keystore/my-release-key.jks \
            -PKEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }} \
            -PKEY_ALIAS=${{ secrets.KEY_ALIAS }} \
            -PKEY_PASSWORD=${{ secrets.KEY_PASSWORD }}

      - name: Find APK file
        id: find_apk
        run: |
          APK_PATH=$(find app/build/outputs/apk/release -name "*.apk" | head -n 1)
          echo "apk_path=$APK_PATH" >> $GITHUB_OUTPUT
          echo "Found APK: $APK_PATH"

      - name: Create GitHub Release and upload APK
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.find_apk.outputs.apk_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
